[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "exqudens-py-sphinx"
version = "1.0.0"
description = "Exqudens Sphinx"
requires-python = ">=3.10"
dependencies = [
    "Sphinx==6.2.1",
    "linuxdoc==20230506",
    "breathe==4.35.0",
    "mlx.traceability==10.0.0",
    "docxbuilder==1.2.0",
    "docxbuilder[math]",
    "rst2pdf==0.100"
]

[project.optional-dependencies]
pyinstaller = [
    "pyinstaller==6.1.0"
]
test = [
    "pytest==7.4.0"
]
